version: '3.8'
services:
  web:
    image: web
    restart: unless-stopped
    build:
      context: .
      args:
        ENVIRONMENT: prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck: # 添加健康检测
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health-check" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

  mysql:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./scripts/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"